### ISSUE TITLE
Where is repository of website?

### ISSUE THREAD

**Issue by VsyachePuz** [GNU-Pony/hoofbook#1]
I want to read hoofbook in browser, but don't know the url

How this distribution is better than all others (beside of art)?
How friendship and magic affects code of conduct (like https://www.mageia.org/ru/about/code-of-conduct/)?
Which package manager is used (exherbo or not, and why)?
Is there an installer for distribution? (like Anakonda or Calamares)
Which utility automates initramfs creation?
Which profiles for which desktop environmets exist (Mate, Gnome3, KDE, Xfce)?
Which services are used as infrastructure beside github? Is repository mirrored on bitbucket?
How one can create wiki for this site on his national language?
and so on

**Comment by maandree** [comment]
The hoofbook has not be compiled to HTML yet.
So to read it, you have to clone its repository, run make
and open one of the compiled documents (for example
the PDF file that will be located at the root of the repo.)

Currently, running getting started with GNU/Pony takes some work,
and the package manager (https://github.com/GNU-Pony/spike) is not
finished yet. It has been some time, since I worked on GNU/Pony,
but I have not given up, I have some other (private) projects of high
priority that takes most of by spare time right now.

And to answer some of your other question.

There aer no wiki:s, because I do not think it is worth the time
to write them. All projects are documented using Texinfo,
which can be compiled to info, pdf, and html, among other
formats. This gives it the advantage that the documentation
is readily available even without an Internet connection, and
and can be made accessible on the Internet; as well as made
available as a dead fluttershy edition.

Currently there are no mirrors. And GitHub is the only used
service. This may change when it becomes more usable.

Currently there are no desktop environments in the software
repository, however, there is a desktop manager project
(https://github.com/GNU-Pony/rarity) of low priority. The default
will be to not install any display server (X, Mir, Wayland …)
but there will be a tool that helps you install collections of
packages (based on user personas) that will include such
things. At least one profile, will install all of them, and use
a display manager (https://github.com/GNU-Pony/exdm) that
previews display and describes the desktop environment so
that you can make a more informed choice.

Currently, there are is no automation of initramfs creation.
This will probably change in the future.

Friendship and magic will probably not effect the code of
conduct much (I don't see how it could,) other than being
written in ponified English. That is if there will even be a
code of conduct.

GNU/Pony is not just a ponified computing experinces,
I am building my dread distribution and it will include
(sometimes not as default however) all my favourite
projects, and those are often written by myself. Some
difference from most other distributions is that it will
more configurable (like Gentoo), be more minimal (like
Gentoo, more so than Arch Linux), it will not make
non-free packages visible by default, and it will not use
systemd by default.

**Comment by maandree** [comment]
I think I forgot one thing: there will (probably) be an
installer, custom written for GNU/Pony. But the preferred
method will be to install everything manually, since this
is always the most flexible alternative. Installers are usually
used to make it easy for newcommers to GNU/Linux; they
should not have the delusion that GNU/Pony is a good
choice for beginners. (At least not in the beginning.)
